# ----
# Site

title: Aviator
description: Jekyll template for API documentation.
url: https://doc.xt.com
google_analytics_key:
permalink: pretty
baseurl: https://doc.xt.com

# -----
# Build

timezone: Etc/UTC

collections:
  documentation:
    title: Documentation
    position_number: 1
  quotes:
    title: 行情数据
    position_number: 2
  trade:
    title: 交易 API
    position_number: 3
  websocket:
    title: WEBSOCKET
    position_number: 4
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENSE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      type: "documentation"
    values:
      _hide_content: true
  -
    scope:
      type: "quotes"
    values:
      _hide_content: true
  -
    scope:
      type: "trade"
    values:
      _hide_content: true
  -
    scope:
      type: "websocket"
    values:
      _hide_content: true
# -----------
# CloudCannon

types:
  - get
  - put
  - delete
  - post

languages:
  bash: Bash
  c: C
  css: CSS
  html: HTML
  java: Java
  javascript: JavaScript
  json: JSON
  php: PHP
  python: Python
  ruby: Ruby

_options:
  content_markdown:
    format: p h4 h5 h6
    bold: true
    italic: true
    link: true
    bulletedlist: true
    numberedlist: true
    image: true
    table: true
    styles: /css/editor.css
